# -*- coding: utf-8 -*-
"""BE_ML_COOLAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UUcOCkAPe4cx8Eb8XrkwWOj1vRHYO3kQ
"""


"""# Nouvelle section"""

"""pip install split-folders"""

import splitfolders
import tensorflow as tf
from tensorflow.keras import datasets, layers, models, optimizers
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt
from keras.callbacks import EarlyStopping, ModelCheckpoint
from tensorflow.keras.applications import VGG16


from tensorflow.keras.models import load_model
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.callbacks import ReduceLROnPlateau, ModelCheckpoint, EarlyStopping

from tensorflow import keras


############################################################
# Augmentation de donné

# # chemain d'acces pour le dossier d'entree et le dossier de sortie pour les donnees augmentees
# input_dir = '/content/drive/MyDrive/DATA'
# output_dir = "/content/drive/MyDrive/DATA_AUG"

# classe = ["actinic keratosis", "basal cell carcinoma", "dermatofibroma",
#           "melanoma", "nevus", "pigmented benign keratosis", "seborrheic keratosis",
#           "squamous cell carcinoma", "vascular lesion"]


#### pretraitement des donnees
datagen= ImageDataGenerator(rescale=1./255)


train_generator=datagen.flow_from_directory(
    r"C:\Users\ML\Desktop\bureau_etude\DATA_AUG_SPLIT\train",
    target_size=(224, 224),
    color_mode="rgb",
    batch_size=32,
    class_mode="categorical",
    shuffle=True,
    seed=42
    )

test_generator=datagen.flow_from_directory(
    r"C:\Users\ML\Desktop\bureau_etude\DATA_AUG_SPLIT\test",
    target_size=(224, 224),
    color_mode="rgb",
    batch_size=32,
    class_mode="categorical",
    shuffle=False,
    seed=42
    )


val_generator=datagen.flow_from_directory(
    r"C:\Users\ML\Desktop\bureau_etude\DATA_AUG_SPLIT\val",
    target_size=(224, 224),
    color_mode="rgb",
    batch_size=32,
    class_mode="categorical",
    shuffle=True,
    seed=42
    )

# number of outputs = number of digits
NB_CLASSES = 9

# nouveau model avec finiTuning

base_model = VGG16(include_top=False, weights='imagenet', input_shape=(224, 224, 3))
# Include_top=False: pour choisir uniquement les couches convolutives
# weights='imagenet': pour choisir les paramètres entraînés avec la base ImageNet
# il est possible d’adapter input_shape au format des images en entrée de votre réseau


# Les paramètres des 17 premières couches sont gelés
for layer in base_model.layers[:17]:
    layer.trainable = False


# Pour voir quelles sont les couches entraînables
for i, layer in enumerate(base_model.layers):
    print(i, layer.name, layer.trainable)


model = models.Sequential([
 base_model,
 layers.Flatten(),
 #layers.GlobalAveragePooling2D(),

 # layers.Dense(250, activation='relu'),
 # layers.Dropout(0.3),

 # layers.Dense(1000, activation='relu'),
 # layers.Dropout(0.5),
 layers.Dense(250, activation='relu'),
 layers.Dropout(0.3),
 # layers.Dense(125, activation='relu'),
 # layers.Dropout(0.25),
 # layers.Dense(20, activation='relu'),
 layers.Dense(NB_CLASSES, activation='softmax')
])


# summary of the model
model.summary()

# # compiling the model
model.compile(optimizer='SGD', loss='categorical_crossentropy',metrics=['accuracy'])


#training the model
EPOCHS = 50

es = EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience=6)
model_checkpoint = ModelCheckpoint('best_model0904.h5', monitor='val_loss', save_best_only=True)

callbacks = [es, model_checkpoint];

history=model.fit(train_generator, epochs=EPOCHS,verbose=1 ,validation_data=val_generator,callbacks=callbacks)
print(history.history.keys())



#tracer les couche
plt.plot(history.history['loss'], label='train_loss')
plt.plot(history.history['val_loss'], label='val_loss')
plt.legend()
plt.show()

plt.plot(history.history['accuracy'], label='train_accuracy' )
plt.plot(history.history['val_accuracy'], label='val_accuracy')
plt.legend()
plt.show()



#evaluate the model
test_loss, test_acc = model.evaluate(test_generator)
print('Test accuracy:', test_acc)






###########################################################################
# Sauvegarde architecture
model_json1 = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json1)
    model.save_weights("model1.h5")











    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    